apiVersion: v1
kind: Deployment
metadata:
  name: ${project.artifactId}
spec:
  template:
    spec:
      containers:
        - env:
            - name: DB_USERNAME
              valueFrom:
                 secretKeyRef:
                   name: my-database-secret
                   key: user
            - name: DB_PASSWORD
              valueFrom:
                 secretKeyRef:
                   name: my-database-secret
                   key: password
            - name: GC_MAX_METASPACE_SIZE
              value: "150"
            - name: JAVA_OPTIONS
              value: "-Dswarm.datasources.data-sources.MyDS.connection-url=jdbc:h2:mem:fruits;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE -Dswarm.datasources.data-sources.MyDS.user-name=sa -Dswarm.datasources.data-sources.MyDS.password=sa -Dswarm.datasources.data-sources.MyDS.driver-name=h2"
